name: Automatic pull request review
on: 
    pull_request:
    push:
      branches:
        - 'master'
        - 'develop'
jobs:
  automate-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create commits
      run: |
            git config user.name 'TheRadDani'
            git config user.email 'theraddani@users.noreply.github.com'
            date +%s > report.txt
            git commit -am "Modify tracked file during workflow"
            date +%s > new-report.txt
            git add -A
            git commit -m "Add untracked file during workflow"
    - name: Uncommitted change
      run: date +%s > report.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
